---
title: 'Linear Regression: OLS Asymptotics'
date: "2023/7/22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


> Learning points:
>



# Normally Distributed Error Terms

```{r}
# set the random seed
set.seed(1234567)

# set true parameters: intercept & slopes
b0 <- 1; b1 <- 0.5

#initialize ybar to a vector of length r=10000 for storing results
b1hat <- numeric(10000)

par(mfrow=c(2,2))

for (n in c(5,10,100,1000)) {
  # draw a sample of x, fixed over replications:
  x <- rnorm(n,4,1)
  
  # repeat 10000 times
  for (j in 1:10000) {
    # draw a sample of u
    u <-  rnorm(n)
    # draw a sample of y
    y <- b0 + b1*x + u
    # regress y on x and store slope estimate at position j
    bhat <- coef( lm(y~x) )
    b1hat[j] <- bhat["x"]
  }
  plot(density(b1hat), main = "", paste("n =", n, sep = " "))
  curve( dnorm(x, 0.5, sqrt(var(b1hat))), add = TRUE, lty = 2 )
}

# add main title
mtext(expression(paste("Density of ", hat(beta)[1], " with different sample sizes: normal error terms", sep = " ")), side = 3, line = -2, outer = TRUE)
```

# Non-Normal Error Terms

```{r}
# set the random seed
set.seed(1234567)

# set true parameters: intercept & slopes
b0 <- 1; b1 <- 0.5

#initialize ybar to a vector of length r=10000 for storing results
b1hat <- numeric(10000)

par(mfrow=c(2,2))

for (n in c(5,10,100,1000)) {
  # draw a sample of x, fixed over replications:
  x <- rnorm(n,4,1)
  
  # repeat 10000 times
  for (j in 1:10000) {
    # draw a sample of u
    u <-  ( rchisq(n,1)-1 ) / sqrt(2)
    # draw a sample of y
    y <- b0 + b1*x + u
    # regress y on x and store slope estimate at position j
    bhat <- coef( lm(y~x) )
    b1hat[j] <- bhat["x"]
  }
  plot(density(b1hat), main = "", paste("n =", n, sep = " "))
  curve( dnorm(x, 0.5, sqrt(var(b1hat))), add = TRUE, lty = 2 )
}

# add main title
mtext(expression(paste("Density of ", hat(beta)[1], " with different sample sizes: non-normal error terms", sep = " ")), side = 3, line = -2, outer = TRUE)
```

