---
title: 'Instrumental Variables Estimation and Two Stage Least Squares'
date: "2023/7/4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


> Learning points:
>
> * calculate heteroskedasticity robust standard errors using `coeftest()` function
> * F-test under heteroskedasticity assumption using `linearHypothesis()` function
> * use `ggplot()` function of the `ggplot2` package



# Return to education for married women

```{r message=FALSE, warning=FALSE}
library(AER); library(stargazer); library(wooldridge)
data(mroz)

# restrict to non-missing wage observations
oursample <- subset(mroz, !is.na(wage))

# OLS slope parameter manually
with(oursample, cov(log(wage),educ) / var(educ))

# IV slope parameter manually
with(oursample, cov(log(wage),fatheduc) / cov(educ,fatheduc))

# OLS automatically
reg.ols <- lm(log(wage) ~ educ, data=oursample)

# IV automatically
reg.iv <- ivreg(log(wage) ~ educ | fatheduc, data=oursample)

# pretty regression table
stargazer(reg.ols, reg.iv, type="text")

```


```{r}
# Example 15.2 on p. 502
data(wage2)

# IV automatically
reg.iv2 <- ivreg(log(wage) ~ educ | sibs, data=wage2)
stargazer(reg.iv2, type="text")
```

```{r}
# Complete Example 15.2

# load the data
data(wage2, package="wooldridge")

# variable educ and sibs are correlated
reg <- lm(educ ~ sibs, data = wage2)
stargazer(reg, type = "text")

# run the ols and iv estimation
olsreg <- lm(log(wage) ~ educ, data = wage2)
ivreg1 <- ivreg(log(wage) ~ educ | sibs, data = wage2)

# compare the result
stargazer(olsreg, ivreg1, type = "text")
```

